#!/usr/bin/env sh

set -e

PROTOTYPE_NAME="$1"
HEROKU_REMOTE="heroku-$PROTOTYPE_NAME"

if [ -z $PROTOTYPE_NAME ]; then
  echo "ERROR: You must specify a prototype name, e.g. $ create_prototype my-fancy-prototype"
  exit 1
fi

git checkout master
git reset origin/master --hard
git checkout -b $PROTOTYPE_NAME
git push -u origin $PROTOTYPE_NAME

heroku create --remote $HEROKU_REMOTE
cat HEROKU-COLLABORATORS.txt | xargs -I% heroku sharing:add % --remote $HEROKU_REMOTE

./deploy
