source 'https://rubygems.org'

ruby '2.1.2'

gem 'activemodel'
gem 'foreman'
gem 'govuk_frontend_toolkit'
gem 'phonelib'
gem 'puma'
gem 'sass'
gem 'sinatra-contrib'
gem 'sinatra'
gem 'slimmer'
gem 'tilt-govspeak'
gem 'twilio-ruby'
